// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4opr0mPTWYEmTAFGjAZjWyyL8K_tep4s',
    appId: '1:275688518288:web:c8751baf2397a2c328de15',
    messagingSenderId: '275688518288',
    projectId: 'sagamok-members',
    authDomain: 'sagamok-members.firebaseapp.com',
    storageBucket: 'sagamok-members.appspot.com',
    measurementId: 'G-FG9NLKK9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyOo2piIgionEhXtvweFXJjDGMGOiAio',
    appId: '1:275688518288:android:93bbf4e6bffb5ace28de15',
    messagingSenderId: '275688518288',
    projectId: 'sagamok-members',
    storageBucket: 'sagamok-members.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPgElH2Zqdv66oky1V3zR4d1rj-PgE3II',
    appId: '1:275688518288:ios:318b989efa6c909b28de15',
    messagingSenderId: '275688518288',
    projectId: 'sagamok-members',
    storageBucket: 'sagamok-members.appspot.com',
    iosBundleId: 'com.example.sagamokMembers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPgElH2Zqdv66oky1V3zR4d1rj-PgE3II',
    appId: '1:275688518288:ios:42928402b39a14e228de15',
    messagingSenderId: '275688518288',
    projectId: 'sagamok-members',
    storageBucket: 'sagamok-members.appspot.com',
    iosBundleId: 'com.example.sagamokMembers.RunnerTests',
  );
}
